from pathlib import Path

import pytest

from omnigent_migrate.exporter import ExportInvalid, export
from omnigent_migrate.ir import Bundle


def _solo() -> Bundle:
    return Bundle(config={
        "spec_version": 1, "name": "demo", "description": "d",
        "executor": {"type": "omnigent", "config": {"harness": "claude-native"}},
        "prompt": "You are a coding agent.\n",
        "os_env": {"type": "caller_process", "cwd": ".", "sandbox": {"type": "none"}},
    })


def test_export_solo_validates(tmp_path: Path) -> None:
    out = export(_solo(), tmp_path / "bundle")
    assert (out / "config.yaml").is_file()
    text = (out / "config.yaml").read_text()
    assert text.startswith("# GENERATED by omnigent-migrate")


def test_export_orchestrator_with_agents(tmp_path: Path) -> None:
    b = _solo()
    b.config["spawn"] = True
    b.config["tools"] = {"agents": ["reviewer"]}
    b.agents["reviewer"] = {
        "spec_version": 1, "name": "reviewer", "description": "r",
        "executor": {"type": "omnigent", "config": {"harness": "claude-native"}},
        "prompt": "You review diffs.\n",
        "os_env": {"type": "caller_process", "cwd": ".", "sandbox": {"type": "none"}},
    }
    out = export(b, tmp_path / "bundle")
    assert (out / "agents" / "reviewer" / "config.yaml").is_file()


def test_export_invalid_raises(tmp_path: Path) -> None:
    bad = Bundle(config={"spec_version": 1, "executor": {"type": "omnigent", "config": {"harness": "nope"}}})
    with pytest.raises(ExportInvalid):
        export(bad, tmp_path / "bundle")


def test_export_writes_extensions_sidecar(tmp_path: Path) -> None:
    b = _solo()
    b.extensions["hooks"] = {"PreToolUse": [{"matcher": "Bash"}]}
    out = export(b, tmp_path / "bundle")
    sidecar = out / "MIGRATION_EXTENSIONS.yaml"
    assert sidecar.is_file()
    assert sidecar.read_text().startswith("# Carried from the source project")


def test_export_no_extensions_no_sidecar(tmp_path: Path) -> None:
    out = export(_solo(), tmp_path / "bundle")
    assert not (out / "MIGRATION_EXTENSIONS.yaml").exists()
