"""Export a Bundle to a validated Omnigent bundle directory (strict: output must be runnable)."""

from __future__ import annotations

import io
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from omnigent_migrate.ir import Bundle

_HEADER = "# GENERATED by omnigent-migrate — do not edit by hand.\n"
_EXT_HEADER = (
    "# Carried from the source project by omnigent-migrate but with no Omnigent\n"
    "# bundle home. NOT loaded by Omnigent — a record so nothing is silently lost.\n"
    "# See MIGRATION_REPORT.md for the manual steps.\n"
)


class ExportInvalid(Exception):
    """The exported bundle failed omnigent.spec.load — a tool bug, not user input."""


def _write_yaml(path: Path, data: dict[str, Any], header: str = _HEADER) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    yaml = YAML()
    yaml.default_flow_style = False
    setattr(yaml, "sort_base_mapping_type_on_output", False)
    buf = io.StringIO()
    yaml.dump(data, buf)
    path.write_text(header + buf.getvalue())


def export(bundle: Bundle, out_dir: Path) -> Path:
    out_dir = out_dir.expanduser()
    _write_yaml(out_dir / "config.yaml", bundle.config)
    for name, cfg in bundle.agents.items():
        _write_yaml(out_dir / "agents" / name / "config.yaml", cfg)
    if bundle.extensions:
        _write_yaml(out_dir / "MIGRATION_EXTENSIONS.yaml", bundle.extensions, header=_EXT_HEADER)

    from omnigent.errors import OmnigentError
    from omnigent.spec import load

    try:
        load(out_dir, expand_env=False, enforce_handler_allowlist=False)
    except (OmnigentError, FileNotFoundError) as exc:
        raise ExportInvalid(f"{out_dir}: {exc}") from exc
    return out_dir
